# training epochs
epochs: 100
## test and save term
test_epoch: 1
save_epoch: 1
## modify epochs for resume
modify_epochs: null

# Dataset setting
## dataset
dataset: modelnet40
## dataset path
dataset_root: ???
train_class_list: [chair]
test_class_list: [chair, car]
batch_size: 32
nworkers: 8
subset: null

# Network settings
## use cuda
device: cuda
## use feature STN
use_feat_trans: true
## number of points in a block
num_points: 2048
## reproducibility
reproducibility: False
## resume training
resume: null

# Optimizer settings
## optimizer name
optim: adam
lr: 0.001
betas: [0.9,0.999]
wd: 0.0001
## scheduler
epoch_size: 20
gamma: 0.5

# other
## seed value
seed: 71
